apps/accounts/urls.py
from django.conf.urls import url
from .views import (
    CheckUserForSignIn, UserRegisterView,
    UserLoginView, user_logout, CheckUserForExist, ProfileUpdate,
    upload_photo, tag_people_search, ProfileUpdateView,
    PasswordUpdateView, add_friend, confirm_friend_request, unfriend, remove_friend,
    ProfileAvatarUploadView)

urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^update-profile/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^update-password/$', PasswordUpdateView.as_view(), name='password-update'),
    # url(r'^profile/(?P<username>\w+)/$', home, name='user-home'),
    url(r'^check_user/$', CheckUserForSignIn.as_view(), name='check_user'),
    url(r'^tag_people_search/$', tag_people_search, name='tag_people_search'),
    url(r'^(?P<username>[\w-]+)/settings/$', ProfileUpdate.as_view(), name='profile.update'),
    url(r'^check/$', CheckUserForExist.as_view(), name='check'),
    url(r'^upload_photo/$', upload_photo, name='upload_photo'),
    url(r'^upload-avatar', ProfileAvatarUploadView.as_view(), name='upload-avatar'),
    url(r'^add_friend/$', add_friend, name='add_friend'),
    url(r'^remove_friend/$', remove_friend, name='remove_friend'),
    url(r'^confirm_friend_request/$', confirm_friend_request, name='confirm_friend_request'),
    url(r'^unfriend/$', unfriend, name='unfriend'),
]

apps/api/urls.py
from django.conf.urls import url

# from apps.api.accounts.views import (
#     UserPasswordUpdateAPIView,
#     UserFriendsListAPIView, UserSignUpAPIView, CheckUsernameAndEmailAPIView,
#     UserProfileUpdateAPIView, UserListAPIView, UsersSearch, UserAvatarUploadAPIView,
#     FriendsListAPIView
# )

# ------------------------------

from apps.api.accounts import views as account_views
from apps.api.arenas import views as arena_views
from apps.api.days import views as day_views
from apps.api.chat import views as chat_views
from apps.api.geodata import views as geodata_views
from apps.api.notifications import views as not_views
from apps.api.posts import views as post_views
from apps.api.sporttypes import views as sporttype_views
from apps.api.trainings import views as training_views

from apps.api.album import views as _album
from apps.api.post import views as _post
from apps.api.photo import views as _photo
from apps.api.video import views as _video
from apps.api.comment import views as _comment
from apps.api.reply import views as _reply

# ------------------------------

# listspatterns = [
#     url(r'^post/$', PostListAPIView.as_view(), name='post'),
#     # url(r'^countries/$', CountryListAPIView.as_view(), name='countries'),
#     url(r'^feed/$', GetFeedListAPIView.as_view(), name='feed'),
#     url(r'^feed-web/$', GetFeedsAndPostsAPIView.as_view(), name='feed-web'),
#     url(r'^comment/$', CommentListAPIView.as_view(), name='comments'),
#     url(r'^reply/$', ReplyListAPIView.as_view(), name='reply'),
#     # url(r'^trainings/$', GetTrainingsAPIView.as_view(), name='trainings'),
#     url(r'^notifications/$', GetNotificationsListAPIView.as_view(), name='nt'),
# ]

urlpatterns = [
    # url(r'^test-url/$', TestForS.as_view(), name='test-url'),
    url(r'^auth/login/$', account_views.UserLoginAPIView.as_view(), name='login'),
    url(r'^get-room/$', chat_views.GetRoom.as_view(), name='get-room'),
    url(r'^auth/register/$', account_views.UserSignUpAPIView.as_view(), name='reg'),
    # url(r'^info/$', CountriesAPIView.as_view(), name='info'),
    # url(r'^list/', include(listspatterns, namespace='list')),
    # url(r'^create/photo$', PhotoCreateAPIView.as_view(), name='create.photo'),
    # url(r'^create/comment/$', CommentCreateAPIView.as_view(), name='create.comment'),
    # url(r'^create/reply/$', ReplyCreateAPIView.as_view(), name='create.reply'),
    # url(r'^create/post/$', CreatePostAPIView.as_view(), name='create.post'),
    # # url(r'^user/(?P<username>[\w-]+)/$', UserDetailSerializer, name='user.detail'),
    # url(r'^user/friends/$', account_views.UserFriendsListAPIView.as_view(), name='user.detail'),
    # url(r'^add-like/$', AddLike.as_view(), name='add-like'),
    # url(r'^get-city/$', geodata_views.CityGetByCountryAPIView.as_view(), name='get-city'),

    # Notifications
    url(r'^notification/list/$', not_views.NotificationListAPIView.as_view(), name='notification.list'),

    # Accounts
    url(r'^profile/(?P<username>[\w-]+)/new-password/$', account_views.UserPasswordUpdateAPIView.as_view(), name='set-new-password'),
    url(r'^profile/(?P<username>[\w-]+)/update-profile/$', account_views.UserProfileUpdateAPIView.as_view(), name='update-profile'),
    url(r'^profile/(?P<username>[\w-]+)/update-avatar/$', account_views.UserAvatarUploadAPIView.as_view(), name='avatar-upload'),
    url(r'^profile/(?P<username>[\w-]+)/detail/$', account_views.UserDetailAPIView.as_view(), name='user.detail'),
    url(r'^profile/check/email-username/$', account_views.CheckUsernameAndEmailAPIView.as_view()),
    url(r'^profile/friendslist/$', account_views.FriendsListAPIView.as_view()),
    url(r'^profile/list/search/$', account_views.UsersSearch.as_view(), name='users-search'),
    url(r'^profile/list/$', account_views.UserListAPIView.as_view(), name='users-list'),

    # Days
    url(r'^days/list/days/$', day_views.DayListAPIView.as_view(), name='days'),

    # Arenas
    url(r'^arena/get/coordinates/$', arena_views.GetArenasCoordinatesAPIView.as_view(), name='get-coordinates'),
    url(r'^arena/list/arenas/$', arena_views.ArenaListAPIView.as_view(), name='arenas'),

    # Trainings
    url(r'^training/list/trainings/$', training_views.GetTrainingsAPIView.as_view(), name='get-coordinates'),
    url(r'^training/detail/trainings/(?P<pk>\d+)$', training_views.TrainingsDetailAPIView.as_view(), name='detail.trainings'),
    url(r'^training/trainings-all/$', training_views.TrainingsListAPIView.as_view(), name='trainings-all'),

    # Sport Types
    url(r'^sporttype/list/types/$', sporttype_views.SportTypeListAPIView.as_view(), name='types'),

    # Follow
    # url(r'^follower/unfollow/$', UnFollowUserAPIView.as_view(), name='user-unfollow'),
    # url(r'^follower/follow/$', FollowUserAPIView.as_view(), name='user-follow'),

    # GeoData
    url(r'^geodata/countries/$', geodata_views.CountriesListAPIView.as_view(), name='countries'),
    url(r'^geodata/cities/$', geodata_views.CityGetByCountryAPIView.as_view(), name='cities'),

    # Post
    url(r'^posts/albums/$', post_views.AlbumListAPIView.as_view(), name='post.album.list'),
    url(r'^posts/album/create$', post_views.AlbumCreateAPIView.as_view(), name='post.album.create'),
    url(r'^posts/comment/update/(?P<id>\d+)/$', post_views.CommentUpdateAPIView.as_view(), name='post.comment.update'),
    url(r'^posts/comment/delete/(?P<id>\d+)/$', post_views.CommentDeleteAPIView.as_view(), name='post.comment.delete'),
    url(r'^posts/comments/$', post_views.CommentListAPIView.as_view(), name='post.comments'),
    url(r'^posts/reply/update/(?P<id>\d+)/$', post_views.ReplyUpdateAPIView.as_view(), name='post.reply.update'),
    url(r'^posts/reply/delete/(?P<id>\d+)/$', post_views.ReplyDeleteAPIView.as_view(), name='post.reply.delete'),
    url(r'^posts/replies/$', post_views.ReplyListAPIView.as_view(), name='post.replies'),
    url(r'^posts/photos/$', post_views.PhotoListAPIView.as_view(), name='post.photo.list'),
    url(r'^posts/videos/$', post_views.VideoListAPIView.as_view(), name='post.video.list'),
    url(r'^posts/list/$', post_views.GetFeedsAndPostsAPIView.as_view(), name='post.list'),
    url(r'^posts/create/photo$', post_views.PhotoCreateAPIView.as_view(), name='post.create.photo'),
    url(r'^posts/create/comment/$', post_views.CommentCreateAPIView.as_view(), name='post.create.comment'),
    url(r'^posts/create/reply/$', post_views.ReplyCreateAPIView.as_view(), name='post.create.reply'),
    url(r'^posts/create/post/$', post_views.CreatePostAPIView.as_view(), name='post.create.post'),
    url(r'^posts/xaxa/$', post_views.PostListAPIView.as_view(), name='post.xaxa'),

    # **************************************************************************************************************** #

    url(r'^sporttype/list/$', sporttype_views.SportTypeListAPIView.as_view(), name='sporttype.list'),
    url(r'^sporttype/create/$', sporttype_views.SportTypeCreateAPIView.as_view(), name='sporttype.create'),
    url(r'^sporttype/detail/(?P<id>\d+)/$', sporttype_views.SportTypeDetailAPIView.as_view(), name='sporttype.detail'),
    url(r'^sporttype/update/(?P<id>\d+)/$', sporttype_views.SportTypeUpdateAPIView.as_view(), name='sporttype.update'),
    url(r'^sporttype/delete/(?P<id>\d+)/$', sporttype_views.SportTypeDeleteAPIView.as_view(), name='sporttype.delete'),

    url(r'^geo-data/country/list/$', geodata_views.CountriesListAPIView.as_view(), name='country.list'),
    url(r'^geo-data/country/detail/(?P<id>\d+)/$', geodata_views.CountryDetailAPIView.as_view(), name='country.detail'),
    url(r'^geo-data/country/update/(?P<id>\d+)/$', geodata_views.CountryUpdateAPIView.as_view(), name='country.update'),
    url(r'^geo-data/country/delete/(?P<id>\d+)/$', geodata_views.CountryDeleteAPIView.as_view(), name='country.delete'),
    url(r'^geo-data/city/list/$', geodata_views.CityGetByCountryAPIView.as_view(), name='city.list'),
    url(r'^geo-data/city/detail/(?P<id>\d+)/$', geodata_views.CityDetailAPIView.as_view(), name='city.detail'),
    url(r'^geo-data/city/update/(?P<id>\d+)/$', geodata_views.CityUpdateAPIView.as_view(), name='city.update'),
    url(r'^geo-data/city/delete/(?P<id>\d+)/$', geodata_views.CityDeleteAPIView.as_view(), name='city.delete'),


    # **************************************************************************************************************** #

    url(r'^user/list/$', account_views.UserProfileListAPIView.as_view(), name='user.list'),
    url(r'^user/detail/(?P<id>\d+)/$', account_views.UserProfileDetailAPIView.as_view(), name='user.detail'),


    url(r'album/list/$', _album.AlbumListAPIView.as_view(), name="_album.list"),
    url(r'album/detail/(?P<id>\d+)/$', _album.AlbumDetailAPIView.as_view(), name="_album.detail"),
    url(r'album/delete/(?P<id>\d+)/$', _album.AlbumDeleteAPIView.as_view(), name="_album.delete"),
    url(r'album/update/(?P<id>\d+)/$', _album.AlbumUpdateAPIView.as_view(), name="_album.update"),
    # TODO UPDATE APIView
    # TODO CREATE APIView

    url(r'post/list/', _post.PostListAPIView.as_view(), name="_post.list"),
    url(r'post/detail/(?P<id>\d+)/$', _post.PostDetailAPIView.as_view(), name="_post.detail"),
    url(r'post/delete/(?P<id>\d+)/$', _post.PostDeleteAPIView.as_view(), name="_post.delete"),
    # TODO UPDATE APIView
    # TODO CREATE APIView

    url(r'photo/list/', _photo.PhotoListAPIView.as_view(), name="photo.list"),
    url(r'photo/detail/(?P<id>\d+)/$', _photo.PhotoDetailAPIView.as_view(), name="photo.detail"),
    url(r'photo/update/(?P<id>\d+)/$', _photo.PhotoUpdateAPIView.as_view(), name="photo.update"),
    url(r'photo/delete/(?P<id>\d+)/$', _photo.PhotoDeleteAPIView.as_view(), name="photo.delete"),
    # TODO CREATE APIView

    url(r'video/list/', _video.VideoListAPIView.as_view(), name="video.list"),
    url(r'video/detail/(?P<id>\d+)/$', _video.VideoDetailAPIView.as_view(), name="video.detail"),
    url(r'video/update/(?P<id>\d+)/$', _video.VideoUpdateAPIView.as_view(), name="video.update"),

apps/main/urls.py
from django.conf.urls import url

from apps.accounts.views import ProfileUpdate

from .views import menu, gallery, friends, chat


urlpatterns = [
    url(r'^u/(?P<username>[\w-]+)/search/$', friends.search_users, name='user.search'),
    url(r'^u/(?P<username>[\w-]+)/gallery/album-html/$', gallery.GalleryDetailHTMLView.as_view(), name='user.gallery.detail-html'),
    url(r'^u/(?P<username>[\w-]+)/gallery/album/$', gallery.GalleryDetailView.as_view(), name='user.gallery.detail'),

    url(r'^u/(?P<username>[\w-]+)/results/$', friends.search_users_result, name='user.search.results'),

    # Chat
    url(r'^messages_h_old/$', chat.messages_h, name='user.messages_h'),
    url(r'^messages_h/$', chat.messages_h_new, name='user.messages_h'),
    # url(r'^map/$', main_map, name='map'),

    # Menu
    url(
        r'^$',
        menu.home,
        name='user.index'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/gallery/$',
        menu.GalleryView.as_view(),
        name='user.gallery.list'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/settings/$',
        ProfileUpdate.as_view(),
        name='user.settings'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/feed/$',
        menu.MainUserFeedView.as_view(),
        name='user.feed'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/friends/$',
        menu.MainFriendsListView.as_view(),
        name='user.friends'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/chat/$',
        menu.MainUserChatView.as_view(),
        name='user.chat'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/map/$',
        menu.MainUserMapView.as_view(),
        name='user.map'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/trainings/$',
        menu.MyTrainings.as_view(),
        name='user.trainings'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/about_project/$',
        menu.about_project,
        name='user.about_project'
    ),
    url(
        r'^contact/$',
        menu.contact_us,
        name='contact'
    ),
    url(
        r'^u/(?P<username>[\w-]+)/$',
        menu.MainUserHomeView.as_view(),
        name='user.home'
    ),
]

apps/offer/urls.py
from django.conf.urls import url

from apps.offer.views import NewOfferView

urlpatterns = [
    url("^create/$", NewOfferView.as_view(), name="new-offer")
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^activity/', include('apps.activity.urls', namespace='activity')),
    url(r'^account/', include('apps.accounts.urls', namespace='account')),
    url(r'^follow/', include('apps.followers.urls', namespace='follow')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^post/', include('apps.posts.urls', namespace='post')),
    url(r'^_post/', include('apps.post.urls', namespace='_post')),
    url(r'^_album/', include('apps.album.urls', namespace='_album')),
    url(r'^_photo/', include('apps.photo.urls', namespace='_photo')),
    url(r'^_video/', include('apps.video.urls', namespace='_video')),
    url(r'^_like/', include('apps.like.urls', namespace='_like')),
    url(r'^_comment/', include('apps.comment.urls', namespace='_comment')),
    url(r'^_reply/', include('apps.reply.urls', namespace='_reply')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^arena/', include('apps.arenas.urls', namespace='arena')),
    url(r'^training/', include('apps.trainings.urls', namespace='training')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    # url(r'^map/', include('apps.map.urls', namespace='map')),
    url(r'^notifications/', include('apps.notifications.urls', namespace='notifications')),
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

templates/about_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Find your training</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="{% static 'css/semantic.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>
	<!--[if lt IE 9]>
        <script src="assets/js/html5shiv.min.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <script src="assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
</head>
<body>
    <input type="hidden" id="user" value="{{ user.id }}">
    <input type="hidden" id="profile_channel" value="{{ request.user.profile.channel }}">
    <div id="main">
    {% if request.user.is_authenticated %}
        <header class="hd-fixed u-profile">
            <div class="wrapper">
                <div class="up-ls">
                    <div class="up__logo"><a href="/"><img src="{% static 'images/profile/logo.png' %}" title="https://Findyourtraining.com"></a></div>
                    <div class="up__search">
                        <form method="get" action="{% url 'main:user.search' request.user.username %}" id="search-userform">
                            <div class="s-con">
                                <input type="text" id="search-user" name="search" class="f-search" placeholder="Search..." autocomplete="off">
                                <button type="submit" class="btn-s"><i class="search icon"></i></button>
                            </div>
                            <div class="rs-container">
                                <div class="results"></div>
                                <div class="view-all">
                                    <a class="rs-item"></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <nav id="menu">
                    <ul class="txt-uppercase">
                        <li><a href="/">Home</a></li>
                        <li><a href="{% url "main:user.map" request.user.username %}">Map</a></li>
                        <li><a href="#" class="coming_soon">Competition</a></li>
                        <li><a href="#">About project</a></li>
                    </ul>
                </nav>
                <div class="lang-auth">
                    <div id="profile-menu">
                        <div class="profile-wind">
                            <a href="#" class="notify notify-off" data-target="#ppnm">
                                <i class="alarm outline icon"></i>
                                <span class="notify-count">
                                    {% if request.user.profile.notifications_status and request.user.profile.last_notifications > 0 %}
                                        {{ request.user.profile.last_notifications }}
                                    {% endif %}
                                </span>
                            </a>
                            <a href="#" id="pm-trigger" data-target="#p-menu">
                                <span class="profile-img">
                                    <img src="{{ request.user.profile.avatar.url }}"
                                   title="{{ request.user.username }}">
                                </span>
                                <span class="profile-uname">{{ request.user.username }}</span>
                            </a>
                        </div>
                        <div id="ppnm" class="ui popup nm" data-state="off">
                            <div class="nm-ul">
                                <div class="nmul-title">
                                    <a href="#" class="mark-asread">Mark all as read</a>
                                    <h4>Notifications</h4>
                                </div>
                                <div class="nmul-inner">
                                    <div class="new sec">
                                        <div class="content"></div>
                                    </div>
                                    <div class="old sec">
                                        <div class="content"></div>
                                    </div>
                                </div>
                                <div class="nmul-ft">
                                    <a href="#" class="all-notif">All</a>
                                </div>
                            </div>
                        </div>
                        <div class="menu" id="p-menu">
                            <a href="#" class="item">Latest news</a>
                            <a href="#" class="item">Friends</a>
                            <a href="#" class="item coming_soon">Teams</a>
                            <a href="{% url "main:user.map" request.user.username %}" class="item coming_soon">Locations</a>
                            <a href="{% url 'main:user.trainings' user.username %}" class="item">My trainings</a>
                            <a href="#" class="item coming_soon">Training around</a>
                            <a href="#" class="item coming_soon">Competition</a>
                            <a href="#" class="item coming_soon">Gallery</a>
                            <a href="{% url 'main:user.settings' request.user.username %}" class="item">Settings</a>
                            <a href="#" class="item coming_soon">Competition</a>
                            <a href="{% url 'account:logout' %}" class="item logout"><span><i class="sign out icon"></i></span> Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    {% else %}
        <header class="hd-fixed">
            <div class="wrapper">
                <nav id="menu">
                    <ul class="txt-uppercase">
                        <li><a href="/">Home</a></li>
                        <li><a href="#" class="to-auth">Map</a></li>
                        <li><a href="#" class="coming_soon">Competition</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="#">{{ user.username }}</a></li>
                        {% endif %}
                        <li><a href="{% url 'main:contact' %}">About project</a></li>
                    </ul>
                </nav>
                <div class="lang-auth">
                    <div class="la-item la-item__lang">
                        <div id="ch-lang" class="ui selection dropdown">
                            <input type="hidden" name="lang">
                            <i class="dropdown icon"></i>
                            <div class="default text"><i class="us flag"></i><span>English</span></div>
                            <div class="menu">
                                <div class="item" data-value="en"><i class="us flag"></i>English</div>
                                <div class="item" data-value="ru"><i class="ru flag"></i>Russian</div>
                            </div>
                        </div>
                    </div>
                    <div class="la-item la-item__auth"><a href="{% url 'account:login' %}" class="auth">Login</a></div>
				</div>
            </div>
        </header>
    {% endif %}
        <div class="about">
            <div class="about-us">
                <div class="aboutus-txt">
                    <div class="wrapper">
                        <div class="title">
                            <span class="txt-black">About</span>
						    <span class="txt-orange">Project</span>
                        </div>
                        <div class="content">
                            <p>
                                Our map will help you to find all sport activity around you , where ever you ,any city , any country , anywhere all over the world.
						        From calisthenic/fitness parks, running tracks and stadium's, to beautiful and breathtaking places where you can meet like minded people and train together. Again, we are the first company to launch something of this kind in Europe. Not only do we teach you the cooking skills you would like to learn but also educate you on the nutritional value of food throughout the weekend. This weekend is perfect for returning clients and new clients.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="aboutus-pic">
                    <div class="wrapper">
                        <div class="pic"></div>
                    </div>
                    <div class="border-bottom"></div>
                </div>
            </div>
            <div class="about-loc">
                <div class="wrapper">
                    <div class="aboutloc-hd">
                        <span class="txt-black">Our</span>
                        <span class="txt-orange">Offices</span>
                    </div>
                    <div class="row">
                        <a href="#" class="locitem">
                            <div class="inner">
                                <div class="locitem-txt">
                                    <div class="title">Tashkent</div>
                                    <div class="txt">
                                        68а Shota Rustaveli Street<br/>
                                        Yakkasaray district<br/>
                                        Tashkent, 100100<br/>
                                        Uzbekistan
                                    </div>
                                </div>
                                <div class="locitem-pic">
                                    <img src="{% static 'images/map_nyc.jpg' %}" alt="Map of the New York office">
                                </div>
                            </div>
                        </a>
                        <a href="#" class="locitem">
                            <div class="inner">
                                <div class="locitem-txt">
                                    <div class="title">Vancouver</div>
                                    <div class="txt">
                                        1028 Hamilton Street<br/>
                                        Suite 401<br/>
                                        Vancouver, BC, Canada<br/>
                                        V6B2R9
                                    </div>
                                </div>
                                <div class="locitem-pic">
                                    <img src="{% static 'images/map_yvr.jpg' %}" alt="Map of the Vancouver office">
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="about-contact">
                <div class="about-top">
                    <div class="wrapper">
                        <div class="at-title txt-uppercase">Get in touch</div>
                        <div class="at-val">To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from itents.</div>
                    </div>
                </div>
                <div class="aboutform-sec">
                    <div class="wrapper">
                        <div class="about-form">
                            <div class="aform-wrapper">
                                <form action="{% url 'offer:new-offer' %}" method="POST">{% csrf_token %}
                                    <div class="field">
                                        <input type="text" name="name" placeholder="NAME" required>
                                    </div>
                                    <div class="field">
                                        <input type="email" name="email" placeholder="EMAIL" required>
                                    </div>
                                    <div class="field">
                                        <textarea name="message" rows="13" placeholder="MESSAGE" required></textarea>
                                    </div>
                                    <div class="field">
                                        <button type="submit" class="ui orange button txt-uppercase">Send message</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer>
			<div class="wrapper">
				<div class="ccpy"><p>&copy; 2018 All rights reserved<br/>by Findyourtraining | <a href="/" class="txt-orange">Terms / Privacy</a></p></div>
				<div class="cdev"><p>Developed by <a href="https://osg.uz" class="txt-orange">Online Service Group</a></p></div>
			</div>
		</footer>
	</div>
    <div class="ui popup" id="info-p">
        <div class="header">Info</div>
        <div class="content">The referenced page at the design state...</div>
    </div>


	<!-- include jQuery-->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/semantic.min.js' %}"></script>
    <script src="{% static 'js/not_developed_pages_popup.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/notify.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script>
        $(function() {
            $('.ui.dropdown').dropdown();
        });
    </script>
</body>
</html>

templates/post_detail.html
<h1>Here will be detailized post like in facebook</h1>