apps/post/urls.py
from django.conf.urls import url

from .views import (
    PostCreateView
)


urlpatterns = [
    url(r'create', PostCreateView.as_view(), name="create"),
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^activity/', include('apps.activity.urls', namespace='activity')),
    url(r'^account/', include('apps.accounts.urls', namespace='account')),
    url(r'^follow/', include('apps.followers.urls', namespace='follow')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^post/', include('apps.posts.urls', namespace='post')),
    url(r'^_post/', include('apps.post.urls', namespace='_post')),
    url(r'^_album/', include('apps.album.urls', namespace='_album')),
    url(r'^_photo/', include('apps.photo.urls', namespace='_photo')),
    url(r'^_video/', include('apps.video.urls', namespace='_video')),
    url(r'^_like/', include('apps.like.urls', namespace='_like')),
    url(r'^_comment/', include('apps.comment.urls', namespace='_comment')),
    url(r'^_reply/', include('apps.reply.urls', namespace='_reply')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^arena/', include('apps.arenas.urls', namespace='arena')),
    url(r'^training/', include('apps.trainings.urls', namespace='training')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    # url(r'^map/', include('apps.map.urls', namespace='map')),
    url(r'^notifications/', include('apps.notifications.urls', namespace='notifications')),
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

apps/chat/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from channels import Group
from django.core.serializers import serialize

from apps.notifications.models import Notification


class Room(models.Model):
    name = models.CharField(max_length=250)
    users = models.ManyToManyField(User, related_name='room', blank=True)

    @staticmethod
    def get_room_id(user1_id, user2_id):
        ids = [user1_id, user2_id]
        users = User.objects.filter(id__in=ids)
        for room in Room.objects.iterator():
            if set(room.users.all()) == set(users):
                room = room.name
                return room
            else:
                pass

    @staticmethod
    def get_room_name(user1_username, user2_username):
        usernames = [user1_username, user2_username]
        users = User.objects.filter(username__in=usernames)
        for room in Room.objects.iterator():
            if set(room.users.all()) == set(users):
                room = room.id
                return room
            else:
                pass

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', default=0, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', default=0, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    text = models.TextField()
    read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     ordering = ['-created']

    def __str__(self):
        return self.room.name


@receiver(post_save, sender=Message)
def push_notification(sender, instance, created, **kwargs):
    if created:
        if instance.receiver.profile.messages_status:
            Notification.objects.create(
                user=instance.receiver,
                sender=instance.sender,
                text='You have an unread message',
                type_not='chat',
                url=str(instance.receiver.get_absolute_url()) + 'chat/',
            )
        Group('room-{}'.format(instance.receiver.profile.channel)
              ).send({'text': json.dumps(
                  {
                      'id': instance.sender.id,
                      'username': instance.sender.username,
                      'text': instance.text,
                      'type_not': 'chat',
                  }
              )})

apps/api/chat/views.py
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response

from apps.chat.models import Room


class GetRoom(APIView):
    def post(self, request):
        data = request.data
        user1 = data.get('user1')
        user2 = data.get('user2')
        room = Room.get_room_name(user1, user2)
        return Response(data={'room': room})

apps/api/map/views.py
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser

from django.db.models import Q

from apps.geodata.models import Country, State, City
from apps.days.models import Day
from apps.arenas.models import Arena, ArenaImage
from apps.sporttypes.models import SportType
from apps.trainings.models import Training, TrainingImage, TrainingRequest

from apps.api.map.serializers import (
    ArenaListSerializer, TrainingListSerializer, TrainingCreateSerializer,
    DayListSerializer, SportTypeSerializer
)


class DayListAPIView(ListAPIView):
    queryset = Day.objects.all()
    serializer_class = DayListSerializer


class SportTypeListAPIView(ListAPIView):
    queryset = SportType.objects.all()
    serializer_class = SportTypeSerializer


class ArenaListAPIView(ListAPIView):
    serializer_class = ArenaListSerializer

    def get_queryset(self):
        q = self.request.GET.get('name')
        # type_ = self.request.GET.get('type')
        # print(q)
        # print(type_)
        arenas = Arena.objects.all()
        if q:
            arenas = arenas.filter(name__icontains=q)
        # if q and type_:
        #     arenas = arenas.filter(types__name__icontains=type_)
        #     arenas = arenas.filter(
        #         Q(name__icontains=q) |
        #         Q(types__name__icontains=q)
        #     )
        #     print(arenas)
        return arenas


class GetArenasCoordinatesAPIView(APIView):

    def post(self, request):
        c_code = request.data.get('country_code')
        try:
            country = Country.objects.get(code=c_code)
            arenas = Arena.objects.filter(city__in=country.city.all())
        except City.DoesNotExist:
            arenas = []
        arenas = Arena.objects.all()
        serializer = ArenaListSerializer(arenas, many=True)
        return Response(data=serializer.data)


class GetTrainingsAPIView(APIView):
    def post(self, request):
        arena_id = request.data.get('arena_id')
        if arena_id:
            arena_id = int(arena_id)
            trainings = Training.objects.filter(arena_id=arena_id)
            serializer = TrainingListSerializer(trainings, many=True)
            return Response(data=serializer.data)


class TrainingCreateAPIView(CreateAPIView):
    queryset = Training.objects.all()
    serializer_class = TrainingCreateSerializer
    parser_classes = (MultiPartParser, )


# class TraningCreateAPIView(APIView):
#     def post(self, request):
#         print(request.data)
#         Training.objects
#         return Response(data={'status': 'ok'})

class TrainingsListAPIView(ListAPIView):
    serializer_class = TrainingListSerializer

    def get_queryset(self):
        type_ = self.request.GET.get('q')
        date = self.request.GET.get('date')
        trainings = Training.objects.filter(created_by=self.request.user)
        if type_:
            trainings = trainings.filter(types_id=int(type_))
        if date:
            if date == 'asc':
                trainings = trainings.order_by('date')
            elif date == 'desc':
                trainings = trainings.order_by('-date')
        return trainings


class TestForS(APIView):
    def post(self, request):
        print(request.data)
        return Response()


class TrainingsDetailAPIView(RetrieveAPIView):
    queryset = Training.objects.all()
    serializer_class = TrainingListSerializer


class FilterArenasAPiView(ListAPIView):
    serializer_class = ArenaListSerializer

    def get_queryset(self):
        type_ = self.request.GET.get("type")
        arenas = Arena.objects.all()
        if type:
            arenas = arenas.filter(types__in=type_)
        return arenas

apps/chat/views.py
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import reverse

from .models import Room


def get_room_id(request):
    # if request.is_ajax():
    user1 = request.POST.get("user1")
    user2 = request.POST.get("user2")
    room_id = Room.get_room_id(user1, user2)
    cache.set("{}_room_id".format(request.user), room_id)
    return JsonResponse({"url": reverse("main")})

apps/main/views/chat.py
from django.contrib.auth.models import User
from django.http import JsonResponse


from apps.chat.models import Room, Message


def messages_h(request):
    sender = User.objects.get(id=request.POST.get('user'))
    receiver = User.objects.get(id=request.POST.get('user_'))
    room_id = 0
    for room in Room.objects.iterator():
        if sender in room.users.all():
            if receiver in room.users.all():
                room_id = room.id
    data = []
    m = {}
    me = []
    data.append({'sender_avatar': sender.profile.avatar.url,
                 'receiver_avatar': receiver.profile.avatar.url})
    messages = Message.objects.filter(room__id=room_id)
    if request.user == sender:
        for m in messages:
            m.read = True
            m.save()
    for message in messages:
        m = {
            'message_type': 'sent' if sender == message.sender else 'received',
            'sender': message.sender.username,
            'receiver': message.receiver.username,
            'text': message.text,
            'created': message.created
        }
        me.append(m)
    data.append(me)
    return JsonResponse(data, safe=False)


def messages_h_new(request):
    user = request.user
    # user_ = User.objects.get(username__iexact=username)
    room_id = request.POST.get('room_id')
    message_id = request.POST.get('message_id')
    messages = Message.objects.filter(room__name=room_id)

    # Mark all messages as read
    for message in messages:
        if user == message.receiver:
            message.read = True
            message.save()

    if message_id:
        messages = messages.filter(id__lt=message_id).order_by('-id')[:15]
    else:
        messages = messages.order_by('-id')[:15]
    data = []
    for message in messages:
        message_dict = {
            'message_id': message.id,
            'message_type': 'sent' if user == message.sender else 'received',
            'sender': message.sender.username,
            'sender_avatar': message.sender.profile.avatar.url,
            'receiver': message.receiver.username,
            'receiver_avatar': message.receiver.profile.avatar.url,
            'text': message.text,
            'created': message.created
        }
        data.append(message_dict)
    return JsonResponse(data, safe=False)

apps/main/views/friends.py
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q
from django.urls import reverse

from apps.followers.models import Follow


users_list_search = []
users_list_search_count = []


def search_users_result(request, username):
    user = User.objects.get(username__iexact=username)
    friends = Follow.objects.filter(
        Q(follower=user) | Q(user=user), is_friend=True)
    global users_list_search
    global users_list_search_count
    if not users_list_search_count:
        users_list_search_count = [0]
    if not users_list_search:
        users_list_search = [User.objects.all()]
    users = users_list_search
    context = {
        'users': users,
        'count': users_list_search_count[0],
        'friends': friends,
    }
    return render(request, 'user/results.html', context)


def search_users(request, username):
    q = request.POST.get('search')
    user = User.objects.filter(Q(username__contains=q) |
                               Q(first_name__iexact=q) |
                               Q(last_name__iexact=q)).exclude(username=request.user.username)
    preview = []
    global users_list_search
    global users_list_search_count
    users_list_search = [user, ]
    users_list_search_count = [user.count()]
    count = user.count() if user else 0
    for u in user:
        if u.profile.avatar:
            avatar = u.profile.avatar.url
        else:
            avatar = static('images/profile/no_photo_male.png')
        data = {
            'username': u.username,
            'photo': str(avatar),
            'url': str(u.get_absolute_url()),
        }
        preview.append(data)
    if preview:
        users_list = {'data': preview, 'count': count, 'success': 'ok',
                      'url': reverse('main:user.search.results',
                                     kwargs={'username': request.user.username})}
    else:
        users_list = {'success': 'false'}
    return JsonResponse(users_list, safe=False)

apps/main/views/gallery.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View

from apps.posts.models import Album

from apps.utils import utils


class GalleryDetailView(View):
    template_name = 'user/gallery.html'

    def get(self, request, username):
        context = {
            'albums': request.user.album.all()
        }
        user = request.user
        user_ = User.objects.get(username__iexact=username)
        can_follow = utils.can_follow(user, user_)
        can_follow = can_follow if user != user_ else 'myself'
        online_users = User.objects.filter(id__in=utils.get_friends_id(user))
        context = {
            'user': user,
            'user_': user_,
            'online_users': online_users,
            'friends_count': utils.friends_count(user_),
            'can_follow': can_follow,
        }
        return render(request, self.template_name, context)


class GalleryDetailHTMLView(View):
    def post(self, request):
        album_id = request.POST.get('album_id')
        if album_id:
            album = Album.objects.get(id=int(album_id))
        html = """
        <h1>""" + album.name + """</h1>
        """
        return HttpResponse(html, content_type='text/html')

templates/user/chat.html
{% extends 'user/base.html' %}

{% block content %}
    <h1>chat page</h1>
    
{% endblock %}

templates/user/feed.html
{% extends 'user/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
{% endblock %}

{% block content %}
    <div class="fl-wrapper">
        {% if request.user == user_ %}
            <div class="u-post">
                <div class="pr-overlay">
                    <div class="cssload-container">
                    <div class="cssload-speeding-wheel"></div>
                    </div>
                </div>
                <form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data" id="post-form">
                    <input type="hidden" name="owner" value="{{ request.user.id }}">
                    <div class="p-attachment">
                        <label class="pa pa-photo" for="inputfile"><i class="photo icon"></i><span>Photo</span></label>
                        <label class="pa pa-video" for="inputfile"><i class="record icon"></i> <span>Video</span></label>
                        <label class="pa pa-file" for="inputfile"><i class="attach icon"></i> <span>File</span></label>
                        <input type="file" id="inputfile" name="file" accept="image/*, video/*" multiple>
                    </div>
                    <div class="form-gr">
                        <textarea name="context" id="post-text" placeholder="What do you plan to do"></textarea>
                    </div>
                    <div class="p-external" style="display: none;">
                        <a href="#"><i class="icon friends"></i> <span>Tag people</span></a>
                        <a href="#"><i class="icon around"></i> <span>Check in</span></a>
                    </div>
                    <div class="pexternal-con" style="display: none;">
                        <div class="tagpeople-area">
                        </div>
                    </div>
                    <div class="pmedia-preview">
                        <label class="pmpreview-img pm-add display-off" for="inputfile"><i class="plus icon"></i></label>
                    </div>
                    <div class="p-submit"><button type="submit" id="post-btn" class="ui orange button txt-uppercase">POST</button></div>
                </form>
            </div>
        {% endif %}
        <div class="feed-list"></div>
    </div>
    <div id="adds-area">
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner1.jpg' %}" alt="240x320" title="240x320">
{#            <span>Здесь могла быть ваша реклама</span>#}
        </a>
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner2.jpg' %}" alt="240x320" title="240x320">
        </a>
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner3.png' %}" alt="240x320" title="240x320">
        </a>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/post.js' %}"></script>
    <script src="{% static 'js/post-feed-load.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script>
      $(function() {

        $('[data-fancybox]').fancybox({
          loop: true,
          buttons : [
            'zoom',
            'close'
          ]
        });

      });
    </script>
{% endblock %}

templates/user/gallery.html
{% extends 'user/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile-gallery.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
{% endblock %}

{% block content %}

    <section class="gallery-section">
        <header>
            <h3 class="section-hd">Gallery(<span class="galitems-count">478</span>)</h3>
        </header>
        <div class="tabsarea">
            <div class="tabsarea-header">
                <div class="tab-links">
                    <a href="#tab-gallery" class="tab-link__item active">Gallery</a>
                    <a href="#tab-albums" class="tab-link__item">Albums</a>
                </div>
            </div>
            <div class="tabsarea-content">
                <div class="tab-content active" id="tab-gallery">
                    <div class="btn-area">
                        <div class="btn-wrapper">
                            <button type="button" data-pid="add-photovideo" data-ptype="photovid" class="modal-trigger ui orange button txt-uppercase">Add photo/video</button>
                        </div>
                    </div>
                    <div class="tab-inner">
                        <div class="row">
                            {% for file in files %}
                                {% if file.image %}
                                    <div class="gal-item col">
                                        <a href="{{ file.image.url }}" data-fbcustom="gal-item" data-type="image" class="media-block media-img" data-id="{{ file.id }}">
                                            <span class="hover-icon"></span>
                                            <span class="edit-btn" data-pid="edit-photovideo" data-ptype="photo" title="Edit item"></span>
                                            <img src="{{ file.image.url }}">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if file.video %}
                                    <div class="gal-item col">
                                        <a href="/_video/video/{{ file.id }}/" data-fbcustom="gal-item" data-type="iframe" class="media-block media-video" data-id="{{ file.id }}">
                                            <span class="hover-icon"></span>
                                            <span class="edit-btn" data-pid="edit-photovideo" data-ptype="vid" title="Edit item"></span>
                                            <img src="{{ file.thumbnail.url }}">
                                        </a>
                                    </div>
                                {% endif %}
                            {% empty %}
                                <div class="ui visible message mlist-empty">
                                  <p>Gallery list is empty!</p>
                                </div>
                            {% endfor %}


    {#                        {% for photo in request.user.new_photos.all %}#}
    {#                            <div class="gal-item col">#}
    {#                                <a href="#" class="media-block media-img">#}
    {#                                    <span class="hover-icon"></span>#}
    {#                                    <span class="edit-btn" data-pid="#edit-photovideo" title="Edit item"></span>#}
    {#                                    <img src="{{ photo.image.url }}">#}
    {#                                </a>#}
    {#                            </div>#}
    {#                        {% endfor %}#}
    {#                        {% for video in request.user.new_videos.all %}#}
    {#                            <div class="gal-item col">#}
    {#                                <a href="#" class="media-block media-video">#}
    {#                                    <span class="hover-icon"></span>#}
    {#                                    <span class="edit-btn" data-pid="#edit-photovideo" title="Edit item"></span>#}
    {#                                    <img src="{{ video.thumbnail.url }}">#}
    {#                                </a>#}
    {#                            </div>#}
    {#                        {% endfor %}#}
                        </div>
                    </div>
                </div>
                <div class="tab-content" id="tab-albums">
                    <div class="btn-area">
                        <div class="btn-wrapper">
                            <button type="button" data-pid="album-create" data-ptype="album" class="modal-trigger ui orange button txt-uppercase">Create album</button>
                        </div>
                    </div>
                    <div class="tab-inner">
                         <div class="row">
                            {% for album in albums %}
                                <div class="gal-item col">
                                    <a href="#" class="gal-detail" data-id="{{ album.id }}">
                                        <div class="media-block media-smash">
                                            <span class="edit-btn" title="Edit album" data-ptype="album" data-pid="album-edit"></span>
                                            <img src="{{ album.album_art.url }}">
                                            <span class="media-count">
                                                <span class="item-count img"><span class="count">{{ album.photo.count }}</span></span>
                                                <span class="item-count video"><span class="count">{{ album.video.count }}</span></span>
                                            </span>
                                        </div>
                                        <div class="media-title">{{ album.name }}</div>
                                    </a>
                                </div>
                            {% empty %}
                                <div class="ui visible message mlist-empty">
                                  <p>Album list is empty!</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="ui modal gal serv-modal" data-title="">
      <div class="header txt-uppercase"><div class="txt"></div><span class="close" data-pid="" title="Close"><i class="remove circle outline icon"></i></span></div>
      <div class="content">
      </div>
    </div>


{% endblock %}

{% block script %}
    <script src="{% static 'js/profile-gallery.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script>
        $(function() {

        });
    </script>
{% endblock %}

templates/user/home.html
{% extends 'user/base.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
{% endblock %}

{% block content %}
<input type="hidden" id="getcom" name="getcom" value="{% url 'api:post.comments' %}">
<input type="hidden" id="getrpl" name="getrpl" value="{% url 'api:post.replies' %}">
    <div class="fl-wrapper">
        {% if request.user == user_ %}
            <div class="u-post">
                <div class="pr-overlay">
                    <div class="cssload-container">
                    <div class="cssload-speeding-wheel"></div>
                    </div>
                </div>
                <form action="{% url '_post:create' %}" method="POST" enctype="multipart/form-data" id="post-form">
                    <input type="hidden" name="owner" value="{{ request.user.id }}">
                    <div class="p-attachment">
                        <label class="pa pa-photo" for="inputfile"><i class="photo icon"></i><span>Photo</span></label>
                        <label class="pa pa-video" for="inputfile"><i class="record icon"></i> <span>Video</span></label>
                        <label class="pa pa-file" for="inputfile"><i class="attach icon"></i> <span>File</span></label>
                        <input type="file" id="inputfile" name="file" accept="image/*, video/*" multiple>
                    </div>
                    <div class="form-gr">
                        <textarea name="context" id="post-text" placeholder="What do you plan to do"></textarea>
                    </div>
                    <div class="p-external" style="display: none;">
                        <a href="#"><i class="icon friends"></i> <span>Tag people</span></a>
                        <a href="#"><i class="icon around"></i> <span>Check in</span></a>
                    </div>
                    <div class="pexternal-con" style="display: none;">
                        <div class="tagpeople-area">
{#                            <div class="field-con">#}
{#                                <input type="hidden" name="receipt" value="">#}
{#                                <div class="fcon-inner">#}
{#                                    <input type="text" class="search" autocomplete="off" tabindex="0">#}
{#                                </div>#}
{#                                <span class="input-sizer"></span>#}
{#                                <div class="res-menu">#}
{#                                    <div class="res__menu-item"></div>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </div>
                    <div class="pmedia-preview">
                        <label class="pmpreview-img pm-add display-off" for="inputfile"><i class="plus icon"></i></label>
                    </div>
                    <div class="p-submit"><button type="submit" id="post-btn" class="ui orange button txt-uppercase">POST</button></div>
                </form>
            </div>
        {% endif %}
        <div class="feed-list"></div>
    </div>
    <div id="adds-area">
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner1.jpg' %}" alt="240x320" title="240x320">
{#            <span>Здесь могла быть ваша реклама</span>#}
        </a>
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner2.jpg' %}" alt="240x320" title="240x320">
        </a>
        <a href="#" class="test-content">
            <img src="{% static 'images/banners/banner3.png' %}" alt="240x320" title="240x320">
        </a>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/post.js' %}"></script>
    <script src="{% static 'js/post-home-load.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script>
      $(function() {
        $('.ui.fluid.multiple.search.dropdown').dropdown();


        $('[data-fancybox]').fancybox({});
        $.fancybox.defaults.animationEffect = "fade";
        $.fancybox.defaults.loop = true;
        $.fancybox.defaults.buttons = [
          'zoom',
          'close'
        ];

      });
    </script>
{% endblock %}